#!/usr/bin/env bash
# setup-env.sh — create or patch .env with all required defaults.
#
# Behaviour:
#   - If .env does not exist: generate a complete .env (all defaults pre-filled).
#   - If .env exists: append any missing vars with their defaults (never overwrites
#     values the user already set).
#   - Reports what was set and reminds about any vars that still need a real value.

set -euo pipefail

ENV_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/.env"

# ---------------------------------------------------------------------------
# Defaults for every variable used by docker-compose + the app
# ---------------------------------------------------------------------------
declare -A DEFAULTS
DEFAULTS=(
    [POSTGRES_USER]="sre"
    [POSTGRES_PASSWORD]="changeme"
    [POSTGRES_DB]="sre"
    [GRAFANA_ADMIN_USER]="admin"
    [GRAFANA_ADMIN_PASSWORD]="changeme"
    [GRAFANA_DOMAIN]="localhost"
    [PROMETHEUS_URL]="http://prometheus:9090"
    [ALERTMANAGER_URL]="http://localhost:9093"
    [OTLP_ENDPOINT]="http://otel-collector:4317"
    [ENABLE_TRACING]="false"
    [REQUEST_TIMEOUT]="10"
    [SERVICE_NAME]="intelligent-sre-mcp"
    [SLACK_CHANNEL]="#sre-alerts"
    [GITHUB_REPO]="sanketsultan/intelligent-sre-mcp"
    [ANTHROPIC_API_KEY]=""
    [SLACK_BOT_TOKEN]=""
    [SLACK_APP_TOKEN]=""
    [GITHUB_TOKEN]=""
)

# Ordered list so the file is human-readable
ORDERED=(
    POSTGRES_USER POSTGRES_PASSWORD POSTGRES_DB
    GRAFANA_ADMIN_USER GRAFANA_ADMIN_PASSWORD GRAFANA_DOMAIN
    PROMETHEUS_URL ALERTMANAGER_URL OTLP_ENDPOINT
    ENABLE_TRACING REQUEST_TIMEOUT SERVICE_NAME
    ANTHROPIC_API_KEY
    SLACK_BOT_TOKEN SLACK_APP_TOKEN SLACK_CHANNEL
    GITHUB_TOKEN GITHUB_REPO
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
has_var() {
    # Returns 0 (true) if the key appears as a non-commented assignment in the file
    grep -qE "^${1}=" "$ENV_FILE" 2>/dev/null
}

# ---------------------------------------------------------------------------
# Create or patch
# ---------------------------------------------------------------------------
if [ ! -f "$ENV_FILE" ]; then
    echo "Creating .env with local dev defaults..."
    {
        echo "# .env — local development. Generated by scripts/setup-env.sh."
        echo "# Never commit this file to source control."
        echo ""
        echo "# --- Database ---"
        echo "POSTGRES_USER=sre"
        echo "POSTGRES_PASSWORD=changeme"
        echo "POSTGRES_DB=sre"
        echo ""
        echo "# --- Grafana ---"
        echo "GRAFANA_ADMIN_USER=admin"
        echo "GRAFANA_ADMIN_PASSWORD=changeme"
        echo "GRAFANA_DOMAIN=localhost"
        echo ""
        echo "# --- Observability ---"
        echo "PROMETHEUS_URL=http://prometheus:9090"
        echo "ALERTMANAGER_URL=http://localhost:9093"
        echo "OTLP_ENDPOINT=http://otel-collector:4317"
        echo "ENABLE_TRACING=false"
        echo "REQUEST_TIMEOUT=10"
        echo "SERVICE_NAME=intelligent-sre-mcp"
        echo ""
        echo "# --- SRE Agent (REQUIRED to use the agent) ---"
        echo "ANTHROPIC_API_KEY="
        echo ""
        echo "# --- Slack bot (optional) ---"
        echo "SLACK_BOT_TOKEN="
        echo "SLACK_APP_TOKEN="
        echo "SLACK_CHANNEL=#sre-alerts"
        echo ""
        echo "# --- GitHub (optional, for post-mortem issues) ---"
        echo "GITHUB_TOKEN="
        echo "GITHUB_REPO=sanketsultan/intelligent-sre-mcp"
    } > "$ENV_FILE"
    CREATED=1
else
    CREATED=0
    PATCHED=()
    for key in "${ORDERED[@]}"; do
        if ! has_var "$key"; then
            echo "${key}=${DEFAULTS[$key]}" >> "$ENV_FILE"
            PATCHED+=("$key")
        fi
    done
    if [ ${#PATCHED[@]} -gt 0 ]; then
        echo "Patched .env — added missing vars: ${PATCHED[*]}"
    else
        echo ".env is up to date, nothing changed"
    fi
fi

# ---------------------------------------------------------------------------
# Remind about vars that need real values
# ---------------------------------------------------------------------------
echo ""
if ! grep -qE "^ANTHROPIC_API_KEY=.+" "$ENV_FILE" 2>/dev/null; then
    echo "ACTION REQUIRED:"
    echo "  ANTHROPIC_API_KEY is not set. Open .env and paste your key:"
    echo "    open .env"
    echo "  Get a key at: https://console.anthropic.com"
    echo ""
else
    echo "ANTHROPIC_API_KEY is set."
fi

if [ "$CREATED" -eq 1 ]; then
    echo "Optional (for Slack bot):  set SLACK_BOT_TOKEN and SLACK_APP_TOKEN in .env"
    echo "Optional (for GitHub):     set GITHUB_TOKEN in .env"
fi
echo ""
