apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: intelligent-sre

resources:
  - namespace.yaml
  - app/
  - observability/
  - security/

commonLabels:
  project: intelligent-sre-mcp
  managed-by: kustomize
